server:
  port: 9527

Spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getById/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
#            - After=2022-11-13T15:10:03.685+08:00[GMT+08:00]         # 断言，需要在匹配的时间段之后
#            - Before=2022-11-13T21:02:03.685+08:00[GMT+08:00]        # 断言，需要在匹配的时间段之前
#            - Cookie=username,zzxx                                   # 断言，需要在Cookie中匹配该字段
#            - Header=X-Request-Id, \d+                               # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Method=GET                                             # 断言，请求方法要为Get
#            - Host=**.atguigu.com                                    # 断言，主机名要匹配字段
#            - Query=username, \d+                                    # 要有参数名username并且值还要是整数才能路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka